class TesteExcecao(message: String) : Exception(message)

fun main(){
//    var valor = 0
//    try {
//        valor = 5/0
//    } catch (e: ArithmeticException) {
//        println("ART - Divisão por zero não permitida! Entre com novo valor: ")
//        val entrada:Int = readln().toInt()
//        valor = entrada / 5
//    } catch (e: Exception) {
//        println("EXC - Divisão por zero não permitida!")
//    } finally {
//        println("Divisão feita com sucesso")
//        println(valor)
//    }

//    fun lancarExcecao() {
//        // ....
//        throw TesteExcecao("Olá mundo das exceções")
//    }
//    lancarExcecao()

}
